[project]
name = "kbase-sdk-baseclient"
version = "0.1.0"
description = "Base client for the KBase SDK"
readme = "README.md"
authors = [{ name = "KBase Development Team" }]
requires-python = ">=3.12"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.32.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/kbase"]

[dependency-groups]
dev = [
    "ipython==9.6.0",
    "pytest==8.4.2",
    "pytest-cov==7.0.0",
    "semver>=3.0.4",
]

[project.urls]
Homepage = "https://github.com/kbase/kb_sdk_baseclient"
Repository = "https://github.com/kbase/kb_sdk_baseclient"
Issues = "https://github.com/kbase/kb_sdk_baseclient/issues"

[tool.uv]
package = true
